//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlightManagementRadar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CheckIn_Details
    {
        public int Boarding_ID { get; set; }
        public Nullable<int> Flight_ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> PhoneNum { get; set; }
        public string Email { get; set; }
        public Nullable<int> Age { get; set; }
        public string Gender { get; set; }
        public string username { get; set; }
    
        public virtual User_Details User_Details { get; set; }
        public virtual Flight_Data Flight_Data { get; set; }
    }
}
