//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlightManagementRadar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flight_Data
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Flight_Data()
        {
            this.CheckIn_Details = new HashSet<CheckIn_Details>();
        }
    
        public int Flight_ID { get; set; }
        public string Flight_Name { get; set; }
        public string Beginning { get; set; }
        public string Destination { get; set; }
        public System.DateTime Boarding_Time { get; set; }
        public Nullable<double> Fare { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CheckIn_Details> CheckIn_Details { get; set; }
    }
}
