//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlightManagementRadar.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FlightManagementContext : DbContext
    {
        public FlightManagementContext()
            : base("name=FlightManagementContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CheckIn_Details> CheckIn_Details { get; set; }
        public virtual DbSet<Flight_Data> Flight_Data { get; set; }
        public virtual DbSet<User_Details> User_Details { get; set; }
    }
}
