//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlightManagementRadar.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class User_Details
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User_Details()
        {
            this.CheckIn_Details = new HashSet<CheckIn_Details>();
        }
        [MinLength(2,ErrorMessage ="Username Length should be atleast 2")]
        [Display(Name="User Name")]
        public string username { get; set; }
        [MinLength(6,ErrorMessage = "Password Length should be atleast 2")]
        [Display(Name ="Password")]
        public string password { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CheckIn_Details> CheckIn_Details { get; set; }
    }
}
